### ISSUE TITLE
Add support for runtime roles for EMR steps

### ISSUE THREAD

**Issue by dacort** [awslabs/amazon-emr-cli#10]
EMR 6.7.0 and later now support [runtime roles](https://docs.aws.amazon.com/emr/latest/ManagementGuide/emr-steps-runtime-roles.html) that allow you to provide a role to use with a specific Step. 

We should update the `run` command to accept a `--job-role` for EMR on EC2 clusters similar to how we do for EMR Serverless.

**Comment by chrisabbott** [comment]
@dacort Does this still need to be implemented? Can I self-assign?

**Comment by dacort** [comment]
Not being worked on, feel free to contribute and open a PR! Thanks. 😃

**Comment by chrisabbott** [comment]
> Not being worked on, feel free to contribute and open a PR! Thanks. 😃

No problem! Very low-hanging fruit. I tested a few EMR EC2 steps using roles with differently scoped policies, and everything appears to be functioning as expected. Let me know in the PR if you want me to add any additional tests or anything.
