### ISSUE TITLE
Don't find option to configure external jars

### ISSUE THREAD

**Issue by mayurchoubey** [awslabs/amazon-emr-cli#34]
What's the way to add external jars in Spark application.
My requirement is to add Delta Lake jars. 

--conf spark.jars=s3://DOC-EXAMPLE-BUCKET/jars/delta-core_2.12-1.1.0.jar

**Comment by dacort** [comment]
There is a `--spark-submit-opts` option that allows you to provide spark-submit options. 

For your example, you could do:

```
emr run .. --spark-submit-opts "--jars 3://DOC-EXAMPLE-BUCKET/jars/delta-core_2.12-1.1.0.jar"
```

Or you could use `--spark-submit-opts "--conf spark.jars=s3://DOC-EXAMPLE-BUCKET/jars/delta-core_2.12-1.1.0.jar`

I also have an example of this in the emr-serverless-samples repo, but it hasn't been merged yet: https://github.com/aws-samples/emr-serverless-samples/pull/50/files

Feel free to re-open if that doesn't work!
